---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: threadtest2
      labels:
        app: threadtest2
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: threadtest2
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: threadtest2
          annotations:
            realtime: "true"
            rt_runtime_us: "25000"
        spec:
          containers:
          - name: threadtest2
            image: harbor.love.io/library/threadtest:latest
            imagePullPolicy: Always
            resources:
              limits:
                memory: "200Mi"
                cpu: "700m"
              requests:
                memory: "200Mi"
                cpu: "700m"
            securityContext:
              capabilities:
                add:
                  - SYS_NICE
          nodeSelector:
            cputype: amd64

