---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: threadtest
      labels:
        app: threadtest
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: threadtest
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: threadtest
        spec:
          containers:
          - name: threadtest
            image: fir.love.io:3005/threadtest:latest
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                  - SYS_NICE
          nodeSelector:
            cputype: amd64

