name: ci

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    # Use container with docker installed
    container: 
      image: catthehacker/ubuntu:act-latest
      volumes:
        # Need to pass /etc/certs through to the custom container
        - /etc/certs:/etc/certs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd ${{ gitea.workspace }}
      - name: Check /etc/certs
        run: |
          ls /etc/certs
          md5sum /etc/certs/ca.crt
      - name: Build
        uses: https://github.com/addnab/docker-run-action@v3
        with:
          image: fir.love.io:3005/amd64/rhel8-gcc850:latest
          options: --rm --volumes-from=${{ env.JOB_CONTAINER_NAME }}
          run: |
            g++ --version
            cmake3 --version
            cd ${{ gitea.workspace }}
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$PWD/.. $PWD/..
            make install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            debug = true
            [registry."fir.love.io:3005"]
              ca=["/etc/certs/ca.crt"]
            [registry."harbor.love.io"]
              ca=["/etc/certs/ca.crt"]      
      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.love.io
          username: ${{ secrets.HARBOR_ROBOT }}
          password: ${{ secrets.HARBOR_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./Containers/threadtest
          file: ./Containers/threadtest/Dockerfile
          push: true
          #tags: fir.love.io:3005/threadtest:latest, fir.love.io:3005/test/threadtest:${{ github.run_number }}
          tags: harbor.love.io/test/threadtest:latest, harbor.love.io/test/threadtest:${{ github.run_number }}
          platforms: linux/amd64
      - name: Report failure
        if: failure()
        uses: tsickert/discord-webhook@v5.4.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: Gitea
          avatar-url: https://about.gitea.com/gitea-text.svg
          content: "Repo ${{ gitea.repository }} branch ${{ gitea.ref }} build :x:"
      - name: Report success
        if: success()
        uses: tsickert/discord-webhook@v5.4.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          username: Gitea
          avatar-url: https://about.gitea.com/gitea-text.svg
          content: "Repo ${{ gitea.repository }} branch ${{ gitea.ref }} build :white_check_mark:"


         
